### ISSUE TITLE
Add support for precision and scale for decimal type

### ISSUE THREAD

**Issue by GrzesiekGdn** [db-migrate/mysql#3]
I suppose you can do it simply by changing createColumnDef function by adding one another if and using existing variable len (casual length property is inappropriate for decimals), for example:

```
  createColumnDef: function(name, spec, options, tableName) {
    var escapedName = util.format('`%s`', name),
        t = this.mapDataType(spec),
        len;
    if(spec.type === type.DECIMAL) {
       if(spec.precision && spec.scale){
         len = '(' + spec.precision + ',' + spec.scale + ')';
       }
    }
    else if(spec.type !== type.TEXT && spec.type !== type.BLOB) {
      len = spec.length ? util.format('(%s)', spec.length) : '';
      if (t === 'VARCHAR' && len === '') {
        len = '(255)';
      }
    }
    var constraint = this.createColumnConstraint(spec, options, tableName, name);
    return { foreignKey: constraint.foreignKey,
             constraints: [escapedName, t, len, constraint.constraints].join(' ') };
  },
```

Probably it will be more clear to use another variable (not len).

Second idea would be changing base function (from db-migrate-base) but I'm not sure if all databases have decimals with precision and scale. Additionally current function createColumnDef from db-migrate-mysql doesn't use base version so this change would not be sufficient.

I have tested my change and it seems to work and I added pull request with it.
##

**Comment by kusmayadi** [comment]
+1

**Comment by wzrdtales** [comment]
https://github.com/db-migrate/mysql/pull/13
