### ISSUE TITLE
Ignoring invalid configuration option passed to Connection: driver.

### ISSUE THREAD

**Issue by vipulwairagade** [db-migrate/mysql#33]
`Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection`

Please help fix this issue. I have been using this earlier and seemed to be working fine. But since when I changed my database to which I need to connect, it's creating this issue. 

Thanks in advance.

**Comment by vipulwairagade** [comment]
I guess we need to omit `driver` key while making a connection. Please can we expect a newer version release asap.

**Comment by yannic7** [comment]
yeah same here

**Comment by nistic** [comment]
Is a fix ever going to get merged into production?

**Comment by ptrumpis** [comment]
I am having the same problem. 

`Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection`

It is not an error but the ticket is already one year old... I don't want to build projects based on dead dependencies that don't receive maintenance...

**Comment by arjun-mavonic** [comment]
Why don't you delete this repo immediately and force everyone to use typeorm or sequalize or others?
This looks like some timepass college project which nobody now gives a fuck about.

**Comment by arjun-mavonic** [comment]
Your master branch build has all ci tasks failed. That shitty you guys are.

**Comment by wzrdtales** [comment]
lol, feel free to fork or contribute. The db-migrate ecosystem is open. You can always define and maintain your own driver (just needs to start with the name db-migrate- and you can address it in your config).

Otherwise. get your temper together, open source is not there to help you free load, it is a community effort and sharing things. If you plan to invest a sustainable amount of money or time, you can start yelling. If you want to contribute money, the amount needed for a full time dev taking roughly 10% out for this driver is 1250$, feel free to reach out if you want a quote. If you want to contribute, you're very welcome to do so.

Warmly,

the db-migrate team

**Comment by wzrdtales** [comment]
> I am having the same problem.
> 
> `Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection`
> 
> It is not an error but the ticket is already one year old... I don't want to build projects based on dead dependencies that don't receive maintenance...

I stated before this module could need another maintainer, and I am welcoming them btw. The fix that was presented, however did not implement the change requested, this is why this is open. We (as a company) do actively maintain the core, pg and cockroachdb driver.

**Comment by wzrdtales** [comment]
> I am having the same problem.
> 
> `Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection`
> 
> It is not an error but the ticket is already one year old... I don't want to build projects based on dead dependencies that don't receive maintenance...

I stated before this module could need another maintainer, and I am welcoming them btw. The fix that was presented, however did not implement the change requested, this is why this is open. We (as a company) do actively maintain the core, pg and cockroachdb driver, everything else I try to review, but there is no active development. We simply don't use mysql or mariadb anymore, the best maintainer is always someone who actively uses the technology (mysql in this case).
