### ISSUE TITLE
db-migrate-mysql.connect(): do not pass driver option on to mysql.createConnection()

### ISSUE THREAD

**Issue by jfalch** [db-migrate/mysql#45]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `db-migrate-mysql@2.2.0` for the project I'm working on.

warning message when running _db-migrate up_: "Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection"

patched according to https://github.com/db-migrate/node-db-migrate/issues/753#issuecomment-1093264137

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/db-migrate-mysql/index.js b/node_modules/db-migrate-mysql/index.js
index 0c4460d..66841e4 100644
--- a/node_modules/db-migrate-mysql/index.js
+++ b/node_modules/db-migrate-mysql/index.js
@@ -500,6 +500,7 @@ function dummy () {
 
 exports.connect = function (config, intern, callback) {
   let db;
+  delete config.driver;
 
   internals = intern;
   log = internals.mod.log;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by wzrdtales** [comment]
closed as of #41  instead
